server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: app

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/taskmanager}
    username: ${SPRING_DATASOURCE_URL:postgres}
    password: ${SPRING_DATASOURCE_URL:postgres}

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}

logging:
  level:
    root: INFO
    com.javarush: INFO
    com.javarush.config.MdcFilter: INFO
    org.springframework.security: INFO
    org.springframework.web: WARN
    org.springframework.boot.web.servlet: WARN
    org.hibernate: WARN
    org.hibernate.sql: WARN
    org.hibernate.orm.jdbc.bind: WARN
    org.apache: WARN
    com.zaxxer.hikari: WARN
  file:
    name: logs/taskmanager.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30
      total-size-cap: 1GB
      clean-history-on-start: false
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} [reqId=%X{requestId}] [user=%X{user}] [ip=%X{ip}] - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorted: method
    tagsSorted: alpha
  show-actuator: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  metrics:
    tags:
      application: task-manager